name: build plugin

on:
  push:
    paths:
      - 'package.json'
      - 'src/**'
permissions:
  id-token: write
  contents: read
jobs:
  call-pluginworkflow:
    uses: community-khoros/khoros-workflows/.github/workflows/plugin-workflow-usw2.yaml@main
    secrets: inherit

